import { chromium } from 'playwright';
const OUT='/tmp/claude-1000/-work-JobMonitor/2e6742ab-60fe-4876-a415-1fbd300fce7b/scratchpad';
const b=await chromium.launch({headless:true,args:['--no-sandbox']});
const p=await b.newPage({viewport:{width:1100,height:740},deviceScaleFactor:1,colorScheme:'light'});
const errs=[]; p.on('pageerror',e=>errs.push(String(e)));
await p.goto('http://localhost:5191',{waitUntil:'networkidle'});
await p.getByText('Fix fuel mixture calc').waitFor({timeout:15000});
await p.getByText('CI').first().waitFor({timeout:8000});
await p.waitForTimeout(600);
await p.screenshot({path:`${OUT}/26-overview-actions.png`});
console.log('ok; errors:', errs.length?JSON.stringify(errs):'none');
await b.close();
